ALTER TABLE driver
    MODIFY role ENUM ('DRIVER', 'PASSENGER') DEFAULT 'DRIVER' NOT NULL;

ALTER TABLE driver
    MODIFY approval_status ENUM ('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING' NOT NULL;

ALTER TABLE driver
    MODIFY is_active BIT(1) DEFAULT 0 NOT NULL;

ALTER TABLE driver
    MODIFY average_rating DOUBLE DEFAULT 0.0 NOT NULL;

ALTER TABLE passenger
    MODIFY role ENUM ('DRIVER', 'PASSENGER') DEFAULT 'PASSENGER' NOT NULL;

ALTER TABLE passenger
    MODIFY average_rating DOUBLE DEFAULT 0.0 NOT NULL;

